// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqcptlwzhahipkmyudjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxY3B0bHd6aGFoaXBrbXl1ZGp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTE4MTUsImV4cCI6MjA2OTU2NzgxNX0.FnOhqJrm0hTNk69IrnhiP9OgJeGSzqT1czdN6ZkewzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});